### PR TITLE
Muse proto mute setting incorrect

### PR DESCRIPTION
**Pull request by Jason-nz**
GPIO pin 21 is for mute and mine would only output sounds with the switch off, this corrects that.

### CODE REVIEW

**Comment by Jason-nz** [comment]
On second thought, it feels weird to have audio only play with the switch off, but I guess technically with the mute switch on not sounds should come out. 

Maybe this shouldn't be exposed in HA and just always on?

**Review by jesserockz — CHANGES_REQUESTED** [review]
@Jason-nz there is actually a `mute_pin` on the `i2s_audio` media player (that I forgot to document) that should work for this. I just forgot about it when I wrote the proto yaml.

```yaml
media_player:
  - platform: i2s_audio
    ...
    mute_pin: gpio21
```

**Comment by Jason-nz** [comment]
Well should we have a mute switch exposed in HA or should we just turn it on when volume is 0?

**Comment by balloob** [comment]
The media player entity allows muting.

**Comment by Jason-nz** [comment]
Using `mute_pin: GPIO21` only outputs sound when muted, is there a way to invert it?

**Comment by jesserockz** [comment]
Interesting, I would have thought it would be the opposite (not inverted), since it is inverted as a `power` switch.

I dont actually have the board so I cannot test this.

**Comment by Jason-nz** [comment]
Yeah I have:

Screenshot_20220614-092634_Home Assistant~2

It will output sound when muted and if I try to adjust the volume, sound stops coming out (because it unmutes)

**Comment by Jason-nz** [comment]
On here

https://forum.raspiaudio.com/t/muse-proto-board/231

Screenshot_20220614-095651_Chrome~2

It states:

`IO21 enables (true) the amplification`

So I take that to mean:
Pin HIGH = sound
Pin LOW = no sound

https://github.com/esphome/esphome/blob/8998c5f6dd5291c0bfb881dda4068627a51e037a/esphome/components/i2s_audio/i2s_audio_media_player.cpp#L75

This sets the pin HIGH on mute

**Comment by Jason-nz** [comment]
And on here:

https://forums.slimdevices.com/showthread.php?115733-ESPMUSE-LUXE-Speaker&p=1045874

Screenshot_20220614-101359_Chrome~2

**Comment by Jason-nz** [comment]
> Interesting, I would have thought it would be the opposite (not inverted), since it is inverted as a `power` switch.
> 
> I dont actually have the board so I cannot test this.
> 
> Try
> 
> ```yaml
> mute_pin:
>   number: GPIO21
>   inverted: true
> ```

Confirmed with this it works as expected 👍

**Comment by balloob** [comment]
Thanks Jason!

**Pull request merged**
